cloud_deploy_system/cloud_deploy_system/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^us/',include('usweb.urls')),
]

cloud_deploy_system/usweb/urls.py
from django.conf.urls import url
from . import views

app_name = "usweb"

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^files/',views.FilesView.as_view(),name="files"),
    url(r'^update/',views.update,name="update"),
    url(r'^status/',views.status,name="status"),
    url(r'^upload/',views.upload,name="upload"),
    url(r'^about/',views.about,name="about"),
    #url(r'^/user$',views.UserView.as_view(),name="user"),
    #url(r'^/patch$',views.PatchView.as_view(),name="patch"),
]

cloud_deploy_system/usweb/models.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
"""
File Name: models.py
Author: shalk 
Mail: shalk@qq.com
Created Time: 2016-10-09 09:58:27
Description: 
"""
from django.db import models

class  AnsibleAdHoc(models.Model):
    name = models.CharField(max_length=50)
    host_pattern =  models.CharField(max_length=100)
    module = models.CharField(max_length=30)
    args =  models.CharField(max_length=300)
    host_file = models.CharField(max_length=50)

class CloudManager(models.Model):
    name = models.CharField(max_length=50)
    ip = models.GenericIPAddressField()
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

class BashAdHoc(models.Model):
    name = models.CharField(max_length=50)
    cmd =  models.CharField(max_length=300)
     
     
class Files(models.Model):
    name = models.CharField(max_length=50)
    path = models.CharField(max_length=200)

cloud_deploy_system/usweb/views.py
import os

from django.shortcuts import render,get_object_or_404

from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse 
from django.views.generic import ListView,DetailView

from .models import AnsibleAdHoc,CloudManager,Files
import updatesystem
# Create your views here.
from .form import UploadFileForm


def index(request):
    cloudmanager_list = CloudManager.objects.all()
    context = {'cloudmanager_list': cloudmanager_list}
    return render(request,"usweb/index.html",context)

def handle_uploaded_file(f):
    filename = f.name
    cwd = os.path.dirname(__file__)
    filepath = os.path.join(cwd,'static/upload/{}'.format(filename))
    try:
        with open(filepath,'wb+') as dest:
            for chunk in f.chunks():
                dest.write(chunk)
        return filepath
    except Exception as error:
        print(error.message)
        return None

def upload(request,status=None):
    if request.method == 'POST':
        file_path = handle_uploaded_file(request.FILES['myfile'])
        if file_path is not None:
            file1 = Files(name=os.path.basename(file_path),path=file_path)
            file1.save()

        #return HttpResponseRedirect(reverse("usweb:upload"),{'upload_success':True})
        return render(request,"usweb/upload.html",{'upload_success':True})
    else:
        return render(request,"usweb/upload.html",{'upload_success':status})

class AdHocView(DetailView):
    model = AnsibleAdHoc
    template = "usweb/adhoc.html"

class FilesView(ListView):
    model = Files
    template_name = 'usweb/files.html'

def update(request):
    return render(request,"usweb/update.html")

def status(request):
    return render(request,"usweb/status.html")

def about(request):
    return render(request,"usweb/about.html")

def do_check_before(request):
    pass

cloud_deploy_system/usweb/templates/usweb/about.html
{% extends 'usweb/base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>关于</h1>
      <hr>
      <p>本系统主要用于给cloudmanager进行版本升级和补丁升级。</p> 
      <p>也可以自定义ansible命令、bash命令以及ansible playbook，完成系统配置、自动安装以及任务编排的工作。</p>
    </div>
  </div>
</div>
<h1></h1>
{% endblock %}

cloud_deploy_system/usweb/templates/usweb/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>CloudView Update System Web</title>

  <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

  <link href="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
  <!-- canvas-to-blob.min.js is only needed if you wish to resize images before upload.
       This must be loaded before fileinput.min.js -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
  <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
       This must be loaded before fileinput.min.js -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/js/plugins/sortable.min.js" type="text/javascript"></script>
  <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
       This must be loaded before fileinput.min.js -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/js/plugins/purify.min.js" type="text/javascript"></script>
  <!-- the main fileinput plugin file -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/js/fileinput.min.js"></script>
  <!-- optionally if you need a theme like font awesome theme you can include 
      it as mentioned below -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/themes/fa/theme.js"></script>
  <!-- optionally if you need translation for your language then include 
      locale file as mentioned below -->
  <script src="//cdn.bootcss.com/bootstrap-fileinput/4.3.5/js/locales/zh.js"></script>
</head>
<body>
  <!-- head line -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          USWeb 
        </a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="{% url 'usweb:index' %}"> 主页 </a></li>
        <li><a href="{% url 'usweb:files' %}"> 文件</a></li>
        <li><a href="{% url 'usweb:upload' %}">上传</a></li>
        <li><a href="{% url 'usweb:update' %}">升级</a></li>
        <li><a href="{% url 'usweb:status' %}">状态</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'usweb:about' %}">关于</a></li>
      </ul>
    </div>
  </nav>
  {% block body %}
  默认文字
  {% endblock %}
  <script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

cloud_deploy_system/usweb/templates/usweb/files.html
{% extends "usweb/base.html" %}
{% block body %}
<ul>
{% for file in object_list %}
  <li> {{ file.path }}</li>
{% endfor %}
</ul>
{% endblock %}

cloud_deploy_system/usweb/templates/usweb/index.html
{% extends 'usweb/base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <p class="text-left"><strong>cloudmanager 主机列表 如下</strong></p>
    <table class="table table-striped">
      <thead>
        <tr>
          <td>#</td>
          <td>名称</td>
          <td>IP</td>
        </tr>
      </thead>
      <tbody>
      {% if cloudmanager_list %}
        {% for cm in cloudmanager_list %}
          <tr>
            <td>{{ forloop.counter}}</td>
            <td>{{ cm.name }}</td>
            <td>{{ cm.ip }}</td>
          </tr>
        {% endfor %} 
      {% else %}
      <p>there are no  cloudmanager </p>
      {% endif %} 
      </tbody>
    </table>
      
    </div>
  </div>
</div>
<h1></h1>
{% endblock %}

cloud_deploy_system/usweb/templates/usweb/status.html
{% extends "usweb/base.html" %}
{% block body %}
状态
{% endblock %}

cloud_deploy_system/usweb/templates/usweb/update.html
{% extends "usweb/base.html" %}
{% load static from staticfiles %}
<!-- load staticfiles -->
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    

<form action="{% url "usweb:upload" %}" method="post" enctype="multipart/form-data" >
{% csrf_token %}
      <!-- input type="text" name="name" value="这个是text input">
      <br>
      <input type="password" name="pwd" value="123456">
      <br>
      <input type="file" name="myfile" >
      <br>
      <input type="button" name="mybutton" value="Go Go Go!">
      <br>
      a:<input type="checkbox" name="checkit" value="a"><br>
      b:<input type="checkbox" name="checkit" value="b" checked><br>
      c:<input type="checkbox" name="checkit" value="c">
      <br>
      x:<input type="radio" name="cr" value="x">
      <br>
      y:<input type="radio" name="cr" value="y">
      <br>
      z:<input type="radio" name="cr" value="z">
      <br>
      <input type="image" src="{% static "usweb/images/123.png" %}" name="img" >
      <br-->

      <label>上传升级包：</label> <input type="file" name=myfile >
      <br>
      <input type="submit" name="mysubmit" value="上传" >

</form>

    </div>
  </div>
</div>
{% endblock %}

cloud_deploy_system/usweb/templates/usweb/upload.html
{% extends "usweb/base.html" %}
{% block body %}
<form action="{% url "usweb:upload" %}" method="post" enctype="multipart/form-data" >
{% csrf_token %}
  <label for="label1">上传升级包:</label>
  <input type="file" name="myfile">
  <input type="submit" value="上传">
</form>
{% if upload_success %}
<p><strong>上传成功</strong></p>
{% endif %}
{% endblock %}